name: Bot Vote Pixworld

on:
  schedule:
    # S'exécute toutes les 3 heures à 5 minutes (ex: 03:05, 06:05, etc.)
    - cron: '5 */3 * * *'
  workflow_dispatch: # Permet de lancer le test manuellement

jobs:
  vote:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          # Installation de Chrome et des bibliothèques nécessaires
          pip install -r requirements.txt

      - name: Execution du vote
        env:
          MY_EMAIL: ${{ secrets.MY_EMAIL }}
          MY_PASSWORD: ${{ secrets.MY_PASSWORD }}
        run: python vote.py
